# Generated by Django 5.0.7 on 2024-07-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('state', models.CharField(default='InProgress', max_length=10)),
                ('incorrect_guesses', models.IntegerField(default=0)),
                ('correct_guesses', models.CharField(default='', max_length=100)),
                ('max_incorrect_guesses', models.IntegerField()),
            ],
        ),
    ]
