# Generated by Django 5.0.7 on 2024-07-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='revealed_word',
            field=models.CharField(default='', max_length=100),
        ),
    ]
